platform :ios, '12.0'

target 'Purchase DEMO' do
  use_frameworks!

  pod 'SnapKit'
  pod 'SwiftyStoreKit'
  pod 'Alamofire'
  pod 'MMKV'
  
  pod 'LookinServer', :configurations => ['Debug']

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            # config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
           config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
           config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end
